Couldn't subscribe to SAP Build Apps. Please try again. If the problem persists, open a ticket using the BCP component: CA-LCA-ACP.
Technical Details:
subscribe failed. Error: subscribe failed in create callback. Error description: CorrelationId: cbe1eb88-cccd-2c44-c6a9-ae9361ea6d70, Details: Error manage callbacks: Failed to call callback url PUT: https://sms.us10.apps.build.cloud.sap/cloud-runtime/v1/callback/zones/301c47b1-90c1-4380-b216-aa25db901637, correlationId: cbe1eb88-cccd-2c44-c6a9-ae9361ea6d70, app for iasServiceInstanceId: 32dc404d-4353-44c2-99c5-f06c035863f2 and zoneId: 301c47b1-90c1-4380-b216-aa25db901637. Body: IasSubscriptionCallbackPayloadDto(subscriber=IasSubscriptionCallbackSubscriberPayloadDto(subaccountId=301c47b1-90c1-4380-b216-aa25db901637, subaccountSubdomain=buildapps202307281, globalAccountId=20743d31-fe19-4291-b2f7-72a884f104fa, subscriptionGUID=ca8fe32f-c3b0-4d61-873b-5850f940e063, licenseType=SAPPROD, userId=sb-ut-41544b51-a5dc-4201-86d2-3a5a4e60cd5b-clone!b5877|cis-local!b4, crmId=99999996, zoneId=301c47b1-90c1-4380-b216-aa25db901637, app_tid=301c47b1-90c1-4380-b216-aa25db901637, zoneName=, tenantHost=alv7kqzip.accounts.ondemand.com, userInfo=UserInfoPojo(userId=rui.nogueira@sap.com, userGuid=c4f1228a-2570-4673-94a4-d1ae8a5bce38, userName=rui.nogueira@sap.com, email=rui.nogueira@sap.com, subIdp=D045023, sub=c4f1228a-2570-4673-94a4-d1ae8a5bce38)), rootApplication=IasSubscriptionCallbackApplicationPayloadDto(iasServiceInstanceId=a50a01e3-2214-47d9-855b-5f4b9a848f3b, appDisplayName=SAP Build Apps, appName=sap-appgyver-ee, commercialAppName=sap-build-apps, planName=standard, subscriptionParams=null, providerSubaccountId=d50a4906-8cef-452e-b559-66a08e60386e), ownServiceInstance=IasSubscriptionCallbackApplicationPayloadDto(iasServiceInstanceId=32dc404d-4353-44c2-99c5-f06c035863f2, appDisplayName=SAP Build Apps runtime service, appName=null, commercialAppName=null, planName=null, subscriptionParams=null, providerSubaccountId=null), serviceInstances=[IasSubscriptionCallbackServiceInstancePayloadDto(serviceInstanceId=2c944cef-4f89-43b0-b5dd-3d384c06b36c)], eventType=CREATE) Reason: returned value from application: 500 INTERNAL_SERVER_ERROR, with body: {"error":"Internal Server Error"}